// @flow
/* eslint-disable import/prefer-default-export */

export const CREATE_COLUMN: 'CREATE_COLUMN' = 'CREATE_COLUMN';
export const UPDATE_COLUMN: 'UPDATE_COLUMN' = 'UPDATE_COLUMN';
export const UPDATE_COLUMN_SUBSCRIPTIONS: 'UPDATE_COLUMN_SUBSCRIPTIONS' = 'UPDATE_COLUMN_SUBSCRIPTIONS';
export const DELETE_COLUMN: 'DELETE_COLUMN' = 'DELETE_COLUMN';
export const CREATE_SUBSCRIPTION: 'CREATE_SUBSCRIPTION' = 'CREATE_SUBSCRIPTION';
export const UPDATE_SUBSCRIPTION: 'UPDATE_SUBSCRIPTION' = 'UPDATE_SUBSCRIPTION';
export const DELETE_SUBSCRIPTION: 'DELETE_SUBSCRIPTION' = 'DELETE_SUBSCRIPTION';
export const SET_THEME: 'SET_THEME' = 'SET_THEME';
export const STAR_REPO: 'STAR_REPO' = 'STAR_REPO';
export const UNSTAR_REPO: 'UNSTAR_REPO' = 'UNSTAR_REPO';
export const LOAD_SUBSCRIPTION_DATA_REQUEST: 'LOAD_SUBSCRIPTION_DATA_REQUEST' = 'LOAD_SUBSCRIPTION_DATA_REQUEST';
export const LOAD_SUBSCRIPTION_DATA_SUCCESS: 'LOAD_SUBSCRIPTION_DATA_SUCCESS' = 'LOAD_SUBSCRIPTION_DATA_SUCCESS';
export const LOAD_SUBSCRIPTION_DATA_FAILURE: 'LOAD_SUBSCRIPTION_DATA_FAILURE' = 'LOAD_SUBSCRIPTION_DATA_FAILURE';
