// @flow
/* eslint-disable import/prefer-default-export */

// app data
export const CLEAR_APP_DATA: 'CLEAR_APP_DATA' = 'CLEAR_APP_DATA';

// auth
export const LOGIN_REQUEST: 'LOGIN_REQUEST' = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE: 'LOGIN_FAILURE' = 'LOGIN_FAILURE';
export const LOGOUT: 'LOGOUT' = 'LOGOUT';
export const UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER' = 'UPDATE_CURRENT_USER';

// columns
export const CREATE_COLUMN: 'CREATE_COLUMN' = 'CREATE_COLUMN';
export const UPDATE_COLUMN: 'UPDATE_COLUMN' = 'UPDATE_COLUMN';
export const DELETE_COLUMN: 'DELETE_COLUMN' = 'DELETE_COLUMN';

// configs
export const SET_THEME: 'SET_THEME' = 'SET_THEME';

// events
export const CLEAR_EVENTS: 'CLEAR_EVENTS' = 'CLEAR_EVENTS';
export const MARK_EVENTS_AS_SEEN: 'MARK_EVENTS_AS_SEEN' = 'MARK_EVENTS_AS_SEEN';
export const MARK_EVENTS_AS_NOT_SEEN: 'MARK_EVENTS_AS_NOT_SEEN' = 'MARK_EVENTS_AS_NOT_SEEN';

// notifications
export const LOAD_NOTIFICATIONS_REQUEST: 'LOAD_NOTIFICATIONS_REQUEST' = 'LOAD_NOTIFICATIONS_REQUEST';
export const LOAD_NOTIFICATIONS_SUCCESS: 'LOAD_NOTIFICATIONS_SUCCESS' = 'LOAD_NOTIFICATIONS_SUCCESS';
export const LOAD_NOTIFICATIONS_FAILURE: 'LOAD_NOTIFICATIONS_FAILURE' = 'LOAD_NOTIFICATIONS_FAILURE';
export const TOGGLE_SEEN_NOTIFICATION: 'TOGGLE_SEEN_NOTIFICATION' = 'TOGGLE_SEEN_NOTIFICATION';

// repo
export const STAR_REPO: 'STAR_REPO' = 'STAR_REPO';
export const UNSTAR_REPO: 'UNSTAR_REPO' = 'UNSTAR_REPO';
export const TOGGLE_SEEN_EVENT: 'TOGGLE_SEEN_EVENT' = 'TOGGLE_SEEN_EVENT';

// subscriptions
export const CREATE_SUBSCRIPTION: 'CREATE_SUBSCRIPTION' = 'CREATE_SUBSCRIPTION';
export const UPDATE_SUBSCRIPTION: 'UPDATE_SUBSCRIPTION' = 'UPDATE_SUBSCRIPTION';
export const DELETE_SUBSCRIPTION: 'DELETE_SUBSCRIPTION' = 'DELETE_SUBSCRIPTION';
export const UPDATE_COLUMN_SUBSCRIPTIONS: 'UPDATE_COLUMN_SUBSCRIPTIONS' = 'UPDATE_COLUMN_SUBSCRIPTIONS';
export const UPDATE_ALL_COLUMNS_SUBSCRIPTIONS: 'UPDATE_ALL_COLUMNS_SUBSCRIPTIONS' = 'UPDATE_ALL_COLUMNS_SUBSCRIPTIONS';
export const LOAD_SUBSCRIPTION_DATA_REQUEST: 'LOAD_SUBSCRIPTION_DATA_REQUEST' = 'LOAD_SUBSCRIPTION_DATA_REQUEST';
export const LOAD_SUBSCRIPTION_DATA_SUCCESS: 'LOAD_SUBSCRIPTION_DATA_SUCCESS' = 'LOAD_SUBSCRIPTION_DATA_SUCCESS';
export const LOAD_SUBSCRIPTION_DATA_FAILURE: 'LOAD_SUBSCRIPTION_DATA_FAILURE' = 'LOAD_SUBSCRIPTION_DATA_FAILURE';
