// flow-typed signature: 6549a1300874d42c882707feaa6bd707
// flow-typed version: <<STUB>>/bugsnag-react-native_v^1.1.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bugsnag-react-native/lib/Bugsnag' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bugsnag-react-native/index' {
  declare module.exports: $Exports<'bugsnag-react-native'>;
}
declare module 'bugsnag-react-native/index.js' {
  declare module.exports: $Exports<'bugsnag-react-native'>;
}
declare module 'bugsnag-react-native/lib/Bugsnag.js' {
  declare module.exports: $Exports<'bugsnag-react-native/lib/Bugsnag'>;
}
