// flow-typed signature: 779eda4938fc6e1942fa924a47157399
// flow-typed version: <<STUB>>/denormalizr_v^0.4.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'denormalizr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'denormalizr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'denormalizr/lib/ImmutableUtils' {
  declare module.exports: any;
}

declare module 'denormalizr/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'denormalizr/lib/ImmutableUtils.js' {
  declare module.exports: $Exports<'denormalizr/lib/ImmutableUtils'>;
}
declare module 'denormalizr/lib/index.js' {
  declare module.exports: $Exports<'denormalizr/lib/index'>;
}
