// flow-typed signature: 9c7f09fc4f6984104362b66637d945e0
// flow-typed version: <<STUB>>/firebase_v^3.6.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'firebase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'firebase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'firebase/app-node' {
  declare module.exports: any;
}

declare module 'firebase/app' {
  declare module.exports: any;
}

declare module 'firebase/auth-node' {
  declare module.exports: any;
}

declare module 'firebase/auth' {
  declare module.exports: any;
}

declare module 'firebase/database-node' {
  declare module.exports: any;
}

declare module 'firebase/database' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-app-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-client-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-database-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-messaging-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-server-auth-externs' {
  declare module.exports: any;
}

declare module 'firebase/externs/firebase-storage-externs' {
  declare module.exports: any;
}

declare module 'firebase/firebase-app' {
  declare module.exports: any;
}

declare module 'firebase/firebase-auth' {
  declare module.exports: any;
}

declare module 'firebase/firebase-browser' {
  declare module.exports: any;
}

declare module 'firebase/firebase-database' {
  declare module.exports: any;
}

declare module 'firebase/firebase-messaging' {
  declare module.exports: any;
}

declare module 'firebase/firebase-node' {
  declare module.exports: any;
}

declare module 'firebase/firebase-react-native' {
  declare module.exports: any;
}

declare module 'firebase/firebase-storage' {
  declare module.exports: any;
}

declare module 'firebase/firebase' {
  declare module.exports: any;
}

declare module 'firebase/messaging' {
  declare module.exports: any;
}

declare module 'firebase/server-auth-node/auth' {
  declare module.exports: any;
}

declare module 'firebase/server-auth-node/credential' {
  declare module.exports: any;
}

declare module 'firebase/server-auth-node/index' {
  declare module.exports: any;
}

declare module 'firebase/server-auth-node/token-generator' {
  declare module.exports: any;
}

declare module 'firebase/storage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'firebase/app-node.js' {
  declare module.exports: $Exports<'firebase/app-node'>;
}
declare module 'firebase/app.js' {
  declare module.exports: $Exports<'firebase/app'>;
}
declare module 'firebase/auth-node.js' {
  declare module.exports: $Exports<'firebase/auth-node'>;
}
declare module 'firebase/auth.js' {
  declare module.exports: $Exports<'firebase/auth'>;
}
declare module 'firebase/database-node.js' {
  declare module.exports: $Exports<'firebase/database-node'>;
}
declare module 'firebase/database.js' {
  declare module.exports: $Exports<'firebase/database'>;
}
declare module 'firebase/externs/firebase-app-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-app-externs'>;
}
declare module 'firebase/externs/firebase-auth-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-auth-externs'>;
}
declare module 'firebase/externs/firebase-client-auth-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-client-auth-externs'>;
}
declare module 'firebase/externs/firebase-database-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-database-externs'>;
}
declare module 'firebase/externs/firebase-messaging-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-messaging-externs'>;
}
declare module 'firebase/externs/firebase-server-auth-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-server-auth-externs'>;
}
declare module 'firebase/externs/firebase-storage-externs.js' {
  declare module.exports: $Exports<'firebase/externs/firebase-storage-externs'>;
}
declare module 'firebase/firebase-app.js' {
  declare module.exports: $Exports<'firebase/firebase-app'>;
}
declare module 'firebase/firebase-auth.js' {
  declare module.exports: $Exports<'firebase/firebase-auth'>;
}
declare module 'firebase/firebase-browser.js' {
  declare module.exports: $Exports<'firebase/firebase-browser'>;
}
declare module 'firebase/firebase-database.js' {
  declare module.exports: $Exports<'firebase/firebase-database'>;
}
declare module 'firebase/firebase-messaging.js' {
  declare module.exports: $Exports<'firebase/firebase-messaging'>;
}
declare module 'firebase/firebase-node.js' {
  declare module.exports: $Exports<'firebase/firebase-node'>;
}
declare module 'firebase/firebase-react-native.js' {
  declare module.exports: $Exports<'firebase/firebase-react-native'>;
}
declare module 'firebase/firebase-storage.js' {
  declare module.exports: $Exports<'firebase/firebase-storage'>;
}
declare module 'firebase/firebase.js' {
  declare module.exports: $Exports<'firebase/firebase'>;
}
declare module 'firebase/messaging.js' {
  declare module.exports: $Exports<'firebase/messaging'>;
}
declare module 'firebase/server-auth-node/auth.js' {
  declare module.exports: $Exports<'firebase/server-auth-node/auth'>;
}
declare module 'firebase/server-auth-node/credential.js' {
  declare module.exports: $Exports<'firebase/server-auth-node/credential'>;
}
declare module 'firebase/server-auth-node/index.js' {
  declare module.exports: $Exports<'firebase/server-auth-node/index'>;
}
declare module 'firebase/server-auth-node/token-generator.js' {
  declare module.exports: $Exports<'firebase/server-auth-node/token-generator'>;
}
declare module 'firebase/storage.js' {
  declare module.exports: $Exports<'firebase/storage'>;
}
