// flow-typed signature: b75487e162dc48bd433c84c069c641fe
// flow-typed version: <<STUB>>/gravatar_v^1.6.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gravatar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gravatar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gravatar/cli' {
  declare module.exports: any;
}

declare module 'gravatar/lib/gravatar' {
  declare module.exports: any;
}

declare module 'gravatar/test/gravatar.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gravatar/cli.js' {
  declare module.exports: $Exports<'gravatar/cli'>;
}
declare module 'gravatar/index' {
  declare module.exports: $Exports<'gravatar'>;
}
declare module 'gravatar/index.js' {
  declare module.exports: $Exports<'gravatar'>;
}
declare module 'gravatar/lib/gravatar.js' {
  declare module.exports: $Exports<'gravatar/lib/gravatar'>;
}
declare module 'gravatar/test/gravatar.test.js' {
  declare module.exports: $Exports<'gravatar/test/gravatar.test'>;
}
