// flow-typed signature: 4a9b05a6fc2a1640f48d21e95b50308b
// flow-typed version: <<STUB>>/jest-react-native_v17.0.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-react-native/build/bridge-mock' {
  declare module.exports: any;
}

declare module 'jest-react-native/build/index' {
  declare module.exports: any;
}

declare module 'jest-react-native/build/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-react-native/build/bridge-mock.js' {
  declare module.exports: $Exports<'jest-react-native/build/bridge-mock'>;
}
declare module 'jest-react-native/build/index.js' {
  declare module.exports: $Exports<'jest-react-native/build/index'>;
}
declare module 'jest-react-native/build/setup.js' {
  declare module.exports: $Exports<'jest-react-native/build/setup'>;
}
