// flow-typed signature: bc46886deb864a1c3a50ba0f91761eee
// flow-typed version: <<STUB>>/jest-react-native_v^18.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-react-native/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-react-native/build/index.js' {
  declare module.exports: $Exports<'jest-react-native/build/index'>;
}
