// flow-typed signature: e46f3e49e063c7478dd236f705ea0b65
// flow-typed version: <<STUB>>/react-native-linear-gradient_v^1.5.15/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-linear-gradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-linear-gradient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-linear-gradient/Examples/AnimatedGradient/index.android' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/Examples/AnimatedGradient/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/Examples/AnimatedGradient/src/index' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/index.android' {
  declare module.exports: any;
}

declare module 'react-native-linear-gradient/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-linear-gradient/Examples/AnimatedGradient/index.android.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/Examples/AnimatedGradient/index.android'>;
}
declare module 'react-native-linear-gradient/Examples/AnimatedGradient/index.ios.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/Examples/AnimatedGradient/index.ios'>;
}
declare module 'react-native-linear-gradient/Examples/AnimatedGradient/src/index.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/Examples/AnimatedGradient/src/index'>;
}
declare module 'react-native-linear-gradient/index.android.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/index.android'>;
}
declare module 'react-native-linear-gradient/index.ios.js' {
  declare module.exports: $Exports<'react-native-linear-gradient/index.ios'>;
}
