// flow-typed signature: 5322b51d6b9fe7ea79775fde897ed44f
// flow-typed version: <<STUB>>/react-native-oauth_v^2.1.5/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-oauth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-oauth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-oauth/lib/authProviders' {
  declare module.exports: any;
}

declare module 'react-native-oauth/lib/promisify' {
  declare module.exports: any;
}

declare module 'react-native-oauth/react-native-oauth' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-oauth/lib/authProviders.js' {
  declare module.exports: $Exports<'react-native-oauth/lib/authProviders'>;
}
declare module 'react-native-oauth/lib/promisify.js' {
  declare module.exports: $Exports<'react-native-oauth/lib/promisify'>;
}
declare module 'react-native-oauth/react-native-oauth.js' {
  declare module.exports: $Exports<'react-native-oauth/react-native-oauth'>;
}
