// flow-typed signature: f65ebbb0735ae5a0b0e7235ffede542c
// flow-typed version: <<STUB>>/react-native-immutable-list-view_v^0.2.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-immutable-list-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-immutable-list-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-immutable-list-view/lib/ImmutableListView' {
  declare module.exports: any;
}

declare module 'react-native-immutable-list-view/src/__tests__/comparison.test' {
  declare module.exports: any;
}

declare module 'react-native-immutable-list-view/src/__tests__/ImmutableListView.test' {
  declare module.exports: any;
}

declare module 'react-native-immutable-list-view/src/__tests__/testUtils' {
  declare module.exports: any;
}

declare module 'react-native-immutable-list-view/src/ImmutableListView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-immutable-list-view/lib/ImmutableListView.js' {
  declare module.exports: $Exports<'react-native-immutable-list-view/lib/ImmutableListView'>;
}
declare module 'react-native-immutable-list-view/src/__tests__/comparison.test.js' {
  declare module.exports: $Exports<'react-native-immutable-list-view/src/__tests__/comparison.test'>;
}
declare module 'react-native-immutable-list-view/src/__tests__/ImmutableListView.test.js' {
  declare module.exports: $Exports<'react-native-immutable-list-view/src/__tests__/ImmutableListView.test'>;
}
declare module 'react-native-immutable-list-view/src/__tests__/testUtils.js' {
  declare module.exports: $Exports<'react-native-immutable-list-view/src/__tests__/testUtils'>;
}
declare module 'react-native-immutable-list-view/src/ImmutableListView.js' {
  declare module.exports: $Exports<'react-native-immutable-list-view/src/ImmutableListView'>;
}
