// flow-typed signature: d4eb1a1bfe1557e57dc5653b86314fbf
// flow-typed version: <<STUB>>/react-native-actionsheet_v^2.0.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-actionsheet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-actionsheet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-actionsheet/ActionSheetCustom' {
  declare module.exports: any;
}

declare module 'react-native-actionsheet/ActionSheetIOS' {
  declare module.exports: any;
}

declare module 'react-native-actionsheet/Examples/Basic/app' {
  declare module.exports: any;
}

declare module 'react-native-actionsheet/Examples/Basic/index.android' {
  declare module.exports: any;
}

declare module 'react-native-actionsheet/Examples/Basic/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-actionsheet/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-actionsheet/ActionSheetCustom.js' {
  declare module.exports: $Exports<'react-native-actionsheet/ActionSheetCustom'>;
}
declare module 'react-native-actionsheet/ActionSheetIOS.js' {
  declare module.exports: $Exports<'react-native-actionsheet/ActionSheetIOS'>;
}
declare module 'react-native-actionsheet/Examples/Basic/app.js' {
  declare module.exports: $Exports<'react-native-actionsheet/Examples/Basic/app'>;
}
declare module 'react-native-actionsheet/Examples/Basic/index.android.js' {
  declare module.exports: $Exports<'react-native-actionsheet/Examples/Basic/index.android'>;
}
declare module 'react-native-actionsheet/Examples/Basic/index.ios.js' {
  declare module.exports: $Exports<'react-native-actionsheet/Examples/Basic/index.ios'>;
}
declare module 'react-native-actionsheet/index' {
  declare module.exports: $Exports<'react-native-actionsheet'>;
}
declare module 'react-native-actionsheet/index.js' {
  declare module.exports: $Exports<'react-native-actionsheet'>;
}
declare module 'react-native-actionsheet/styles.js' {
  declare module.exports: $Exports<'react-native-actionsheet/styles'>;
}
