// flow-typed signature: 139a90c635572326330c31e97bb63e4f
// flow-typed version: <<STUB>>/react-native-fabric_v^0.3.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fabric'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fabric' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fabric/Answers' {
  declare module.exports: any;
}

declare module 'react-native-fabric/Crashlytics' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fabric/Answers.js' {
  declare module.exports: $Exports<'react-native-fabric/Answers'>;
}
declare module 'react-native-fabric/Crashlytics.js' {
  declare module.exports: $Exports<'react-native-fabric/Crashlytics'>;
}
declare module 'react-native-fabric/index' {
  declare module.exports: $Exports<'react-native-fabric'>;
}
declare module 'react-native-fabric/index.js' {
  declare module.exports: $Exports<'react-native-fabric'>;
}
