// flow-typed signature: af424c93894936023d673d64c12cb40c
// flow-typed version: <<STUB>>/redux-persist-immutable_v^4.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-immutable/constants' {
  declare module.exports: any;
}

declare module 'redux-persist-immutable/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-persist-immutable/lib/index' {
  declare module.exports: any;
}

declare module 'redux-persist-immutable/lib/operators' {
  declare module.exports: any;
}

declare module 'redux-persist-immutable/lib/reconciler' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-immutable/constants.js' {
  declare module.exports: $Exports<'redux-persist-immutable/constants'>;
}
declare module 'redux-persist-immutable/lib/constants.js' {
  declare module.exports: $Exports<'redux-persist-immutable/lib/constants'>;
}
declare module 'redux-persist-immutable/lib/index.js' {
  declare module.exports: $Exports<'redux-persist-immutable/lib/index'>;
}
declare module 'redux-persist-immutable/lib/operators.js' {
  declare module.exports: $Exports<'redux-persist-immutable/lib/operators'>;
}
declare module 'redux-persist-immutable/lib/reconciler.js' {
  declare module.exports: $Exports<'redux-persist-immutable/lib/reconciler'>;
}
