// flow-typed signature: 4e5cb87d4cec8597c6ddbcaf7a0be420
// flow-typed version: <<STUB>>/redux-immutable_v^3.0.9/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-immutable/benchmarks/index' {
  declare module.exports: any;
}

declare module 'redux-immutable/dist/combineReducers' {
  declare module.exports: any;
}

declare module 'redux-immutable/dist/index' {
  declare module.exports: any;
}

declare module 'redux-immutable/dist/utilities/getStateName' {
  declare module.exports: any;
}

declare module 'redux-immutable/dist/utilities/getUnexpectedInvocationParameterMessage' {
  declare module.exports: any;
}

declare module 'redux-immutable/dist/utilities/index' {
  declare module.exports: any;
}

declare module 'redux-immutable/dist/utilities/validateNextState' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-immutable/benchmarks/index.js' {
  declare module.exports: $Exports<'redux-immutable/benchmarks/index'>;
}
declare module 'redux-immutable/dist/combineReducers.js' {
  declare module.exports: $Exports<'redux-immutable/dist/combineReducers'>;
}
declare module 'redux-immutable/dist/index.js' {
  declare module.exports: $Exports<'redux-immutable/dist/index'>;
}
declare module 'redux-immutable/dist/utilities/getStateName.js' {
  declare module.exports: $Exports<'redux-immutable/dist/utilities/getStateName'>;
}
declare module 'redux-immutable/dist/utilities/getUnexpectedInvocationParameterMessage.js' {
  declare module.exports: $Exports<'redux-immutable/dist/utilities/getUnexpectedInvocationParameterMessage'>;
}
declare module 'redux-immutable/dist/utilities/index.js' {
  declare module.exports: $Exports<'redux-immutable/dist/utilities/index'>;
}
declare module 'redux-immutable/dist/utilities/validateNextState.js' {
  declare module.exports: $Exports<'redux-immutable/dist/utilities/validateNextState'>;
}
