// flow-typed signature: 8bcf48557664f66c5dcb1e9a5dded764
// flow-typed version: <<STUB>>/remote-redux-devtools-on-debugger_v^0.7.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remote-redux-devtools-on-debugger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'remote-redux-devtools-on-debugger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remote-redux-devtools-on-debugger/bin/cli' {
  declare module.exports: any;
}

declare module 'remote-redux-devtools-on-debugger/bundle' {
  declare module.exports: any;
}

declare module 'remote-redux-devtools-on-debugger/lib/injectDebugger' {
  declare module.exports: any;
}

declare module 'remote-redux-devtools-on-debugger/lib/injectServer' {
  declare module.exports: any;
}

declare module 'remote-redux-devtools-on-debugger/lib/main' {
  declare module.exports: any;
}

declare module 'remote-redux-devtools-on-debugger/lib/runServer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remote-redux-devtools-on-debugger/bin/cli.js' {
  declare module.exports: $Exports<'remote-redux-devtools-on-debugger/bin/cli'>;
}
declare module 'remote-redux-devtools-on-debugger/bundle.js' {
  declare module.exports: $Exports<'remote-redux-devtools-on-debugger/bundle'>;
}
declare module 'remote-redux-devtools-on-debugger/lib/injectDebugger.js' {
  declare module.exports: $Exports<'remote-redux-devtools-on-debugger/lib/injectDebugger'>;
}
declare module 'remote-redux-devtools-on-debugger/lib/injectServer.js' {
  declare module.exports: $Exports<'remote-redux-devtools-on-debugger/lib/injectServer'>;
}
declare module 'remote-redux-devtools-on-debugger/lib/main.js' {
  declare module.exports: $Exports<'remote-redux-devtools-on-debugger/lib/main'>;
}
declare module 'remote-redux-devtools-on-debugger/lib/runServer.js' {
  declare module.exports: $Exports<'remote-redux-devtools-on-debugger/lib/runServer'>;
}
