// flow-typed signature: 904e1b1fa983112f4add62334225bd84
// flow-typed version: <<STUB>>/warna_v^0.2.4/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'warna'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'warna' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'warna/Gruntfile' {
  declare module.exports: any;
}

declare module 'warna/karma.conf' {
  declare module.exports: any;
}

declare module 'warna/test/test.gradient' {
  declare module.exports: any;
}

declare module 'warna/test/test.parser' {
  declare module.exports: any;
}

declare module 'warna/warna' {
  declare module.exports: any;
}

declare module 'warna/warna.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'warna/Gruntfile.js' {
  declare module.exports: $Exports<'warna/Gruntfile'>;
}
declare module 'warna/karma.conf.js' {
  declare module.exports: $Exports<'warna/karma.conf'>;
}
declare module 'warna/test/test.gradient.js' {
  declare module.exports: $Exports<'warna/test/test.gradient'>;
}
declare module 'warna/test/test.parser.js' {
  declare module.exports: $Exports<'warna/test/test.parser'>;
}
declare module 'warna/warna.js' {
  declare module.exports: $Exports<'warna/warna'>;
}
declare module 'warna/warna.min.js' {
  declare module.exports: $Exports<'warna/warna.min'>;
}
