# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'devhub' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for devhub
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'

end
