source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#use_frameworks!

target 'devhub' do
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
end
